version: '3.4'

services:
  db:
    image: postgres
    volumes:
      - ./api/tmp/db:/var/lib/postgresql/data

  api:
    build: ./api
    volumes:
      - ./api:/docker-api
    command: >
      bash -c "rm -f tmp/pids/server.pid
      && bundle exec rails s -p 3001 -b '0.0.0.0'"
    ports:
      - "3001:3001"
    depends_on:
      - db

  client:
    build: 
      context: ./client
      target: builder
    volumes:
      - ./client:/docker-client
      - node-modules:/docker-client/node_modules
    command: ["npm", "start"]
    ports:
      - "3000:3000"
    depends_on:
      - api

volumes:
  node-modules:
