version: '3'

services:
  db:
    image: postgres
    volumes:
      - ./api/tmp/db:/var/lib/postgresql/data

  api:
    build: api
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3001 -b '0.0.0.0'"
    volumes:
      - ./api:/docker-api
    ports:
      - "3001:3001"
    depends_on:
      - db

  client:
    build: client
    command: "npm start"
    volumes:
      - ./client:/docker-client
      - node-modules:/docker-client/node_modules
    environment:
      - NODE_ENV=development
    ports:
      - "3000:3000"
    depends_on:
      - api

volumes:
  node-modules:
