version: '3'

services:
  db:
    image: postgres
    volumes:
      - ./api/tmp/db:/var/lib/postgresql/data

  api:
    build: api
    volumes:
      - ./api:/docker-api
    environment:
      - PORT=3001
    ports:
      - "3001:3001"
    depends_on:
      - db

  client:
    build: client
    volumes:
      - ./client:/docker-client
      - node-modules:/docker-client/node_modules
    environment:
      - NODE_ENV=development
    ports:
      - "3000:3000"
    depends_on:
      - api

volumes:
  node-modules:
